
language: csharp
solution: ChamberLib.FbxSharp.sln

sudo: false

addons:
  apt:
    packages:
      - nunit-console

script:
  - nuget restore ChamberLib.FbxSharp.sln
  - xbuild /p:Configuration=Debug ChamberLib.FbxSharp.sln
  - mono ./packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./ChamberLib.FbxSharp.Tests/bin/Debug/ChamberLib.FbxSharp.Tests.dll

branches:
  only:
    - master

